### ISSUE TITLE
CodeExport.config.json and CodeExportFileList.conf  

### ISSUE THREAD

**Issue by spences10** [mattpalermo/effoff#5]
Does the vba-ide export need to have the CodeExport.config.json added as a constant i order for this to work?

Also there's a typo in your README

* Works will with the VBA-IDE-Code-Export add-in.

Or is it? I don't know :confused:

**Comment by mattpalermo** [comment]
Yes that is a typo. It should be "works well".

Although I don't understand your first question. For the CodeExport.config.json, you can add a "CustomUI" property to it without effecting the Code-Export add-in. Both programs read the parts of the configuration file which concern them. Although I do suppose there is an issue with the automatic generation of the config file from the add-in. That will remove any CustomUI property that you add to the config file. Not

**Comment by mattpalermo** [comment]
Maybe the automatic config generation needs to get a little bit smarter.

**Comment by spences10** [comment]
I was just wondering if the config file with the VBA-IDE-Export needed to be the same as with effoff for them to work together.

**Comment by spences10** [comment]
>Maybe the automatic config generation needs to get a little bit smarter.

Maybe it does :smile:

**Comment by mattpalermo** [comment]
They could use different files just fine, I chose to use the same file to make it easy for the user and so that maybe in the future they may share parts of the configuration. Although, this does come with the disadvantage of possible conflicts. Do you think it should be separate config files?

Note: I changed the config file name used by the Code-Export add-in when I changed the config to JSON. It is helpful for it to have a .json suffix because text editors will usually use that to enable json specific features such as syntax highlighting.

**Comment by spences10** [comment]
I guess, I mean the file format has gone from plain text to .json now so yeah, apologies this is off topic now :disappointed: but thanks :+1:

**Comment by mattpalermo** [comment]
That's fine. Discussion is good.

**Comment by spences10** [comment]
This can be closed now, yes?
